/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import javax.swing.JOptionPane;
import classes.Sobremesas;

/**
 *
 * @author Aluno: Kamila da Silva Albuquerque <kamilaalbuquerque80@gmail.com>
 * Matrícula: <161080448>
 */
public class TelaSobremesa extends javax.swing.JFrame {

    private static double h;
    private static String i="";
    public TelaSobremesa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSobremesa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        quantS = new javax.swing.JSpinner();
        ok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        tabelaSobremesa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelaSobremesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PETIT GATEAU",  new Double(15.5)},
                {"PUDIM",  new Double(7.5)},
                {"TORTA HOLANDESA",  new Double(9.5)},
                {"MOUSSE",  new Double(5.5)},
                {"PAVÊ",  new Double(6.5)},
                {"DELÍCIA DE ABACAXI",  new Double(7.5)}
            },
            new String [] {
                "SOBREMESA", "VALOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaSobremesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaSobremesaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaSobremesa);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 440, 124);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quantidade:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 290, 75, 15);

        quantS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(quantS);
        quantS.setBounds(110, 290, 41, 22);

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(368, 292, 60, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sobremesas.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-2, 116, 480, 240);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaSobremesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaSobremesaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaSobremesaMouseClicked

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        i="";
        int j = tabelaSobremesa.getSelectedRow();
        int x = (int) quantS.getValue();
        double h = 0;
        if (j != -1 && x>0) {
            Double y =  (Double) tabelaSobremesa.getValueAt(j, 1);
            String w = (String) tabelaSobremesa.getValueAt(j, 0);
            i+=(String) "" + x + " " + w + "\n";
            h+= (double) x*y;
        Sobremesas S = new Sobremesas();
        TelaAddContrato TAC = new TelaAddContrato();
        S.setValorSobremesa(h);
        S.setSobremesas(i);
        TAC.Sobremesas(S);
        this.dispose();
        }
        
        else if (x==0 && j==-1){
            JOptionPane.showMessageDialog(null, "Nenhuma sobremesa adicinado!");
            this.dispose();
        }
        else if(j==-1){
            JOptionPane.showMessageDialog(null, "Selecione a sobremesa que você deseja!");
        }
        else if(x==0){
            JOptionPane.showMessageDialog(null, "Informe a quantidade que você deseja!");
        }
    }//GEN-LAST:event_okActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    private javax.swing.JSpinner quantS;
    private javax.swing.JTable tabelaSobremesa;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the h
     */
    public static double getH() {
        return h;
    }

    /**
     * @param aH the h to set
     */
    public static void setH(double aH) {
        h = aH;
    }
}
