package screens;

import javax.swing.JOptionPane;
import classes.Funcionario;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author
 * Aluno: Kamila da Silva Albuquerque <kamilaalbuquerque80@gmail.com>
 * Matrícula: <161080448>
 */
public class TelaEntrada extends javax.swing.JFrame {

    /**
     * Creates new form Hotel
     */
    public TelaEntrada() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acesso = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        textLogin = new javax.swing.JLabel();
        textsenha = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        Entrar = new javax.swing.JButton();
        foto = new javax.swing.JLabel();
        panelverde = new javax.swing.JPanel();
        hotel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        getContentPane().setLayout(null);

        acesso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        acesso.setText("Acesso de funcionário");
        getContentPane().add(acesso);
        acesso.setBounds(30, 50, 220, 17);

        login.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login.setAlignmentX(1.0F);
        login.setAlignmentY(1.0F);
        login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(360, 90, 200, 22);

        textLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textLogin.setForeground(new java.awt.Color(255, 255, 255));
        textLogin.setText("Login:");
        getContentPane().add(textLogin);
        textLogin.setBounds(310, 90, 50, 20);

        textsenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textsenha.setForeground(new java.awt.Color(255, 255, 255));
        textsenha.setText("Senha:");
        getContentPane().add(textsenha);
        textsenha.setBounds(310, 120, 50, 17);

        senha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        senha.setAlignmentX(1.0F);
        senha.setAlignmentY(1.0F);
        senha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(senha);
        senha.setBounds(360, 120, 200, 22);

        Entrar.setBackground(new java.awt.Color(153, 255, 153));
        Entrar.setText("Entrar");
        Entrar.setAutoscrolls(true);
        Entrar.setBorder(new javax.swing.border.MatteBorder(null));
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar);
        Entrar.setBounds(470, 150, 80, 30);

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1517257867317.jpg"))); // NOI18N
        getContentPane().add(foto);
        foto.setBounds(0, 20, 580, 440);

        panelverde.setBackground(new java.awt.Color(153, 255, 153));

        hotel.setBackground(new java.awt.Color(0, 204, 153));
        hotel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hotel.setText("---Sistema Hotel Campina Confort Premium---");

        javax.swing.GroupLayout panelverdeLayout = new javax.swing.GroupLayout(panelverde);
        panelverde.setLayout(panelverdeLayout);
        panelverdeLayout.setHorizontalGroup(
            panelverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelverdeLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        panelverdeLayout.setVerticalGroup(
            panelverdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelverdeLayout.createSequentialGroup()
                .addComponent(hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(panelverde);
        panelverde.setBounds(0, 0, 580, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        if(login.getText().equalsIgnoreCase("kamila")&&senha.getText().equalsIgnoreCase("12345")){
        new TelaAddContrato().setVisible(true);
        this.dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "Login e/ou senha não conferem.");
        
        
    }//GEN-LAST:event_EntrarActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JLabel acesso;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel hotel;
    javax.swing.JTextField login;
    private javax.swing.JPanel panelverde;
    private javax.swing.JPasswordField senha;
    private javax.swing.JLabel textLogin;
    private javax.swing.JLabel textsenha;
    // End of variables declaration//GEN-END:variables
}
