/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import javax.swing.JOptionPane;
import classes.Drinks;

/**
 *
 * @author Aluno: Kamila da Silva Albuquerque <kamilaalbuquerque80@gmail.com>
 * Matrícula: <161080448>
 */
public class TelaDrink extends javax.swing.JFrame {

    private static double h;
    private static String i="";
    public TelaDrink() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDrink = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        quantD = new javax.swing.JSpinner();
        ok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        tabelaDrink.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelaDrink.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CERVEJA",  new Double(7.0)},
                {"REFRIGERANTE 2 L",  new Double(6.0)},
                {"REFRIGERANTE LATA",  new Double(5.0)},
                {"SUCOS NATURAIS",  new Double(6.0)},
                {"ÁGUA",  new Double(3.0)}
            },
            new String [] {
                "DRINK", "VALOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaDrink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDrinkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDrink);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 440, 108);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quantidade:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(17, 309, 80, 15);

        quantD.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(quantD);
        quantD.setBounds(101, 306, 41, 22);

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(367, 310, 60, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Drink1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 110, 600, 280);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaDrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDrinkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaDrinkMouseClicked

    
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        i="";
        
         int j = tabelaDrink.getSelectedRow();
        int x = (int) quantD.getValue();
        
        if (j != -1 && x>0) {
            Double y =  (Double) tabelaDrink.getValueAt(j, 1);
            String w = (String)  tabelaDrink.getValueAt(j, 0);
            i+=(String) "" + x + " " + w + "\n";
            setH(getH() + (double) x*y);
        
        Drinks D = new Drinks();
        TelaAddContrato TAC = new TelaAddContrato();
        D.setValorBebida(getH());
        D.setDrinks(i);
        TAC.Drinks(D);
        this.dispose();}
        else if (x==0 && j==-1){
            JOptionPane.showMessageDialog(null, "Nenhum drink adicinado!");
            this.dispose();
        }
        else if(j==-1){
            JOptionPane.showMessageDialog(null, "Selecione o drink que você deseja!");
        }
        else if(x==0){
            JOptionPane.showMessageDialog(null, "Informe a quantidade que você deseja!");
        }
        
        
    }//GEN-LAST:event_okActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    private javax.swing.JSpinner quantD;
    private javax.swing.JTable tabelaDrink;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the h
     */
    public static double getH() {
        return h;
    }

    /**
     * @param aH the h to set
     */
    public static void setH(double aH) {
        h = aH;
    }
}
