/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;

import javax.swing.JOptionPane;
import classes.LaCarte;

/**
 *
 * @author Aluno: Kamila da Silva Albuquerque <kamilaalbuquerque80@gmail.com>
 * Matrícula: <161080448>
 */
public class TelaCardapio extends javax.swing.JFrame {

   private static double h;
   private static String i="";
    
    public TelaCardapio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLaCarte = new javax.swing.JTable();
        ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        quantLC = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        tabelaLaCarte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelaLaCarte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CONTRA FILÉ",  new Double(34.9)},
                {"COSTELINHA",  new Double(23.9)},
                {"ESCONDIDINHO",  new Double(33.9)},
                {"FILÉ DE MERLUZA",  new Double(21.9)},
                {"FILÉ MIGNON MOLHO MADEIRA",  new Double(34.9)},
                {"FILÉ À PARMEGIANA",  new Double(36.9)},
                {"FRANGO GRELHADO",  new Double(23.9)},
                {"FRANGO À MILANESA",  new Double(21.9)},
                {"FRANGO À PARMEGIANA",  new Double(26.9)},
                {"LOMBO",  new Double(28.9)},
                {"MACARRONADA",  new Double(22.9)},
                {"MINEIRINHO",  new Double(26.9)},
                {"PERNIL",  new Double(23.9)},
                {"PICANHA",  new Double(37.9)},
                {"PICANHA SUÍNA",  new Double(35.9)},
                {"STROGONOFF FILÉ MIGNON",  new Double(36.9)},
                {"STROGONOFF FRANGO",  new Double(28.9)}
            },
            new String [] {
                "LA CARTE", "VALOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaLaCarte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLaCarteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaLaCarte);
        if (tabelaLaCarte.getColumnModel().getColumnCount() > 0) {
            tabelaLaCarte.getColumnModel().getColumn(0).setHeaderValue("LA CARTE");
            tabelaLaCarte.getColumnModel().getColumn(1).setHeaderValue("VALOR");
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 440, 300);

        ok.setBackground(new java.awt.Color(255, 255, 255));
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(340, 306, 70, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Quantidade:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 311, 90, 15);

        quantLC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(quantLC);
        quantLC.setBounds(120, 310, 41, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pratos_la_carte.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-60, 280, 590, 140);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaLaCarteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLaCarteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaLaCarteMouseClicked

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed

        i="";
        int j = tabelaLaCarte.getSelectedRow();
        int x = (int) quantLC.getValue();
        
        if (j != -1 && x>0) {
            Double y =  (Double) tabelaLaCarte.getValueAt(j, 1);
            String w = (String)  tabelaLaCarte.getValueAt(j,0);
            i+=(String) "" + x + " " + w + "\n";
            h+= (double) x*y;
            
        LaCarte LC = new LaCarte();
        TelaAddContrato TAC = new TelaAddContrato();
        LC.setValorRefeicao(h);
        LC.setLaCarte(i);
        TAC.LaCarte(LC);
        this.dispose();
        }
        else if (x==0 && j==-1){
            JOptionPane.showMessageDialog(null, "Nenhum prato adicinado!");
            this.dispose();
        }
        else if(j==-1){
            JOptionPane.showMessageDialog(null, "Selecione o prato que você deseja!");
        }
        else if(x==0){
            JOptionPane.showMessageDialog(null, "Informe a quantidade que você deseja!");
        }
        
    }//GEN-LAST:event_okActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok;
    private javax.swing.JSpinner quantLC;
    private javax.swing.JTable tabelaLaCarte;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the h
     */
    public static double getH() {
        return h;
    }

    /**
     * @param aH the h to set
     */
    public static void setH(double aH) {
        h = aH;
    }
}
